baseURL: http://anugerah.netlify.app/
languageCode: en-us
title: Anugerah
paginate: 10
theme: "PaperMod"

params:
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true

  label:
    text: "Anugerah"
    icon: "icon-2.png"


  profileMode:
        enabled: true
        title: "Anugerah" # optional default will be site title
        subtitle: "[ Graphic Designer | Video Editor | Film Director | Writer ]"
        imageUrl: "linkedin_01.png" # optional
        imageTitle: "Anugerah's Profile Picture" # optional
        imageWidth: 150 # custom size
        imageHeight: 150 # custom size


  socialIcons: # optional
        - name: GitHub
          url: "https://www.github.com/nugehood"
        - name: Instagram
          url: "https://instagram.com/brief.look"
        - name: YouTube
          url: "https://www.youtube.com/@crunchypie"
        - name: linkedin
          url : "https://www.linkedin.com/in/anugerah-maulana-2ab193175/"
        - name: Email
          url: "mailto:nugehoodg@gmail.com"
        - name: buymeacoffee
          url : "https://www.buymeacoffee.com/nugehood"

menu:
    main:
      - identifier: about
        name: About
        url: /about/
        weight: 1
      - identifier: blogs
        name: Blogs
        url: /blogs/
        weight: 3
      - identifier: gallery
        name: Arts
        url: /gallery/
        weight: 2
      - identifier: video
        name: Videos
        url: /videos/
        weight: 5
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 4